### ISSUE TITLE
Boolean("false") is true

### ISSUE THREAD

**Issue by OmarEltobgy** [adobe/aio-app-scripts#31]
In my node verision (v12.13.0), when the constructor for Boolean (at the line [1]) gets a string "false" as an input, the return is a boolean with a value true. It deals with any non-empty string as a true value. 

One possible solution is to replace this line with (similar to [2]):  
`config.actions.devRemote = Boolean(process.env.REMOTE_ACTIONS === "true")`

[1] https://github.com/adobe/aio-app-scripts/blob/3c6fc2bbfe6f53092fce55f9787513d4de803fb6/lib/config-loader.js#L111
[2] https://stackoverflow.com/a/264037

**Comment by moritzraho** [comment]
fixed in #33
