### ISSUE TITLE
logger is undefined in downloadOWJar function

### ISSUE THREAD

**Issue by OmarEltobgy** [adobe/aio-app-scripts#32]
The function downloadOWJar is called with no logger so when this line [1] tries to log something, it fails

[1] https://github.com/adobe/aio-app-scripts/blob/3c6fc2bbfe6f53092fce55f9787513d4de803fb6/lib/utils.js#L185

This is the place that this function is called from: 
https://github.com/adobe/aio-app-scripts/blob/3c6fc2bbfe6f53092fce55f9787513d4de803fb6/scripts/dev.js#L64

**Comment by moritzraho** [comment]
@OmarEltobgy thank you very much for reporting, fixed in #33
