### ISSUE TITLE
Static folders in /dist directory are not uploaded to CDN

### ISSUE THREAD

**Issue by ahmed-musallam** [adobe/aio-app-scripts#69]
### Expected Behaviour
All subdirectories under my `/dist/web-src-prod` should be uploaded to CDN.

### Actual Behaviour
Only files under `/dist/web-src-prod` are uploaded.

#### Steps to Reproduce

My build process generates a `/dist/web-src-prod` directory that looks like this:

```
.
├── index.html
├── resources // <=== THIS does not get uploaded
│   ├── README.MD
│   ├── spectrum-css-icons.svg
│   ├── spectrum-icons-color.svg
│   └── spectrum-icons.svg
├── src.a2b27638.css
├── src.a2b27638.css.map
├── src.a2b27638.js
├── src.a2b27638.js.map
```

When I run `aio app deploy -v`

I get this in the logs:
```
> Deploy static files
⚠ an already existing deployment for version 0.0.3 will be overwritten
   > static.txt
   > index.html
   > src.a2b27638.css
   > src.a2b27638.css.map
   > src.a2b27638.js
   > src.a2b27638.js.map
✔ Deploy static files
```

I have traced this issue to here: 
https://github.com/adobe/aio-app-scripts/blob/e588449852e0afa53a57dbed290f39f2495d76ca/lib/remote-storage.js#L107

fs-extra does not support recursively walking the filesystem tree, The fs-extra author recommends using `klaw` here: https://github.com/jprichardson/node-fs-extra#what-happened-to-walk-and-walksync
or you could you any number of implementations to get the same result of including the whole directory recursively.

It's missing my `resources` folder

**Comment by moritzraho** [comment]
Hi @ahmed-musallam, thanks for reporting the issue. 
The uploadDir function only uploads a flat directory and doesn't upload nested directories.
We assume that whatever is in `dist/web-src-prod` has been added by `scripts/build.ui.js` which internally uses parcel and outputs built files into a flat directory.

You should add you `resources` folder to `web-src` and link images into your UI code. Then you can build and deploy your app using `@adobe/aio-cli` with the `aio app deploy`command.

**Comment by ahmed-musallam** [comment]
@moritzraho 

Depending on the parcel imports, parcel can also create subdirectories and is **not** constrained to a flat directory.

Even if parcel was constrained to a flat directory, I might want to build my own subdirectories for various reasons or use different parcel plugins to build out subdirectories.

Are you saying that this will not be fixed and the flat directory assumption stands? If that's the case, do you mind telling me why? is it a constraint from your side? or is it just not worth it to fix?

**Comment by moritzraho** [comment]
@ahmed-musallam thanks for the details, I wasn't aware of use cases for uploading recursive directories until now. 
Would you be interested to contribute the fix?

**Comment by ahmed-musallam** [comment]
@moritzraho I sure can, I'm just not sure exactly how to setup all of those projects or just this one as a development project so I can test it locally? any documentation that help?

**Comment by ahmed-musallam** [comment]
@moritzraho fixed. Please take a look and merge. The changes are fairly straight-forward.

**Comment by moritzraho** [comment]
@ahmed-musallam thanks a lot for the contribution, just added a small comment to the PR, once this is resolved we can merge.
