### ISSUE TITLE
deploy fails if name in package.json contains a scope

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-app-scripts#82]
deploy fails if name in package.json contains a scope (starting with `@`)

### Expected Behaviour
deploy should succeed

### Actual Behaviour
deploy fails

### Reproduce Scenario (including but not limited to)
deploy a package with a scope

#### Steps to Reproduce
deploy a package with a scope

#### Platform and Version
current (master)

**Comment by moritzraho** [comment]
yes scoped packages are not supported right now, this is documented in the generated app README https://github.com/adobe/generator-aio-app/blob/master/generators/app/templates/README.md#packagejson

**Comment by moritzraho** [comment]
thanks for raising the issue @tmathern!
Feel free to add next ones in @adobe/aio-cli-plugin-app, so we keep them centralized
